
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='tess-cloud',
    version='0.4.0',
    description='Analyze NASA TESS data in the cloud.',
    python_requires='==3.*,>=3.7.0',
    project_urls={"homepage": "https://github.com/SSDataLab/tess-cloud", "repository": "https://github.com/SSDataLab/tess-cloud"},
    author='Geert Barentsen',
    author_email='hello@geert.io',
    license='MIT',
    keywords='NASA, TESS, Astronomy',
    classifiers=['Intended Audience :: Science/Research', 'Topic :: Scientific/Engineering :: Astronomy'],
    packages=['tess_cloud'],
    package_dir={"": "src"},
    package_data={"tess_cloud": ["data/*.parquet"]},
    install_requires=['aioboto3>=8.2.0', 'aiohttp>=3.7.4', 'astropy>=4.2', 'backoff>=1.10.0', 'diskcache>=5.2.1', 'lightkurve>=2.0.9', 'nest-asyncio==1.*,>=1.5.0,>=1.5.1', 'numpy>=1.19', 'pyarrow>=3.0.0', 's3fs>=0.5.2', 'tess-ephem>=0.3.0', 'tess-locator>=0.5.0', 'tqdm>=4.58.0'],
    extras_require={"dev": ["black==20.*,>=20.8.0.b1", "dephell==0.*,>=0.8.3", "flake8==3.*,>=3.8.4", "isort==5.*,>=5.6.4", "jupyterlab==2.*,>=2.2.9", "line-profiler!=3.2.0,!=3.2.1,<=3.1.0", "memory-profiler==0.*,>=0.58.0", "mkdocs==1.*,>=1.1.2", "mkdocs-material==7.*,>=7.0.6", "mypy==0.*,>=0.790.0", "pytest==6.*,>=6.0.0", "pytest-cov==2.*,>=2.10.1", "pytest-xdist==2.*,>=2.1.0"]},
)
